DROP TABLE USER;

CREATE TABLE USER (
  LOGIN     VARCHAR(32) PRIMARY KEY,
  PSEUDO    VARCHAR(32) NOT NULL,
  PASSWORD  VARCHAR(256) NOT NULL,
  ADMIN     BOOLEAN NOT NULL
);

CREATE TABLE TASK (
  ID            SERIAL PRIMARY KEY,
  DESCRIPTION   VARCHAR(256) NOT NULL,
  AFFECTED_TO   VARCHAR(32),
  DEADLINE      DATE,
  FOREIGN KEY (AFFECTED_TO) REFERENCES USER(LOGIN)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE TABLE 
                                           