DROP TABLE PARTICIPATE;
DROP TABLE TASKS;
DROP TABLE COLUMNS;
DROP TABLE BOARDS;
DROP TABLE USERS;

CREATE TABLE USERS (
  LOGIN     VARCHAR(32) PRIMARY KEY,
  PSEUDO    VARCHAR(32) NOT NULL,
);

CREATE TABLE BOARDS (
  ID_BOARD        SERIAL PRIMARY KEY,
  NAME            VARCHAR(128),
  OWNER           VARCHAR(32) NOT NULL,
  FOREIGN KEY (OWNER) REFERENCES USERS(LOGIN)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE COLUMNS (
  ID_COLUMN     SERIAL PRIMARY KEY,
  BOARD         BIGINT UNSIGNED NOT NULL,
  TITLE         VARCHAR(128),
  FOREIGN KEY (BOARD) REFERENCES BOARDS(ID_BOARD)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE TASKS (
  ID_TASK       SERIAL PRIMARY KEY,
  DESCRIPTION   VARCHAR(256) NOT NULL,
  AFFECTED_TO   VARCHAR(32),
  DEADLINE      DATE,
  COLOR         CHAR(3),
  COL           BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (AFFECTED_TO) REFERENCES USERS(LOGIN)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  FOREIGN KEY (COL) REFERENCES COLUMNS(ID_COLUMN)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE PARTICIPATE (
  PARTICIPANT   VARCHAR(32) NOT NULL,
  BOARD         BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (PARTICIPANT, BOARD),
  FOREIGN KEY (PARTICIPANT) REFERENCES USERS(LOGIN)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (BOARD) REFERENCES BOARDS(ID_BOARD)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
                                           